version: "3"

services:
  app:
    build:
      context: .
      #args:
      #  DB_HOST_ARG: ${DB_HOST}
      #  DB_NAME_ARG: ${DB_NAME}
      #  DB_USER_ARG: ${DB_USER}
      # DB_PASS_ARG: ${DB_PASS}
    volumes:
      - shared_vol:/vol/web
    environment:
      - SECRET_KEY=${{SECRET_KEY}}
      - DEBUG=${DEBUG}}
      - ALLOWED_HOSTS=${{ALLOWED_HOSTS}}
      - DB_HOST=${{DB_HOST}}
      - DB_NAME=${{DB_NAME}}
      - DB_USER=${{DB_USER}}
      - DB_PASS=${{DB_PASS}}

  nginx:
    build:
      context: ./nginx
    volumes:
      - shared_vol:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  shared_vol:
