version: "3"

services:
  app:
    build:
      context: .
      args:
        # db host field value should be the same as the db service name
        - DB_HOST_ARG=db
        - DB_NAME_ARG=app
        - DB_USER_ARG=admin
        - DB_PASS_ARG=Gourav@1996
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Gourav@1996
