version: "3"

services:
  app:
    image: webapp:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      # db host field value should be the same as the db service name
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=admin
      - DB_PASS=postgres_db_pass
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres_db_pass
