version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build and test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Installing docker-compose
          command: pip install docker-compose
      - python/save-cache
      # setup_remote_docker key is only required when the primary executor is a docker container
      # for machines -we do not need to use the setup_remote_docker key
      - setup_remote_docker
      - run:
          name: Build container and run app tests
          # removed flake8 from command for now
          command: |
            docker-compose -f docker-compose.circleci.yml run --name app-container app sh -c "python manage.py test"
      - run:
          name: Copy test results
          when: always
          command: |
            docker start app-container
            docker cp app-container:/app/app/test-results app/app/test-results
      - store_test_results:
          path: app/app/test-results

workflows:
  main:
    jobs:
      - build and test
